import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import { getCurrentSession } from "@/actions/auth";
import { User } from '../generated/prisma/index';
import { SanityLive } from "@/sanity/lib/live";
import HeaderCategorySelector from "./components/layout/HeaderCategorySelector";
import Cart from "./components/Cart/Cart";

const interFont = Inter({subsets: ['latin']})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
  const { user } = await getCurrentSession();
  

  return (
    <html lang="en">
      <body
        className={`${interFont.className} antialiased min-h-[125vh]`}
      >
        <Header user={user} categorySelector={<HeaderCategorySelector />} />
      

        {children}
        <Cart />
        <SanityLive />
      </body>
    </html>
  );
}

export default RootLayout;